version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: college-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: college_db
      POSTGRES_USER: college_user
      POSTGRES_PASSWORD: college_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: